language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - EXCLUDE_TESTS="test_[O-Z].*"
  - EXCLUDE_TESTS="test_[a-ce-zA-N].*"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq rtmpdump
script: nosetests -e $EXCLUDE_TESTS test --verbose
notifications:
  email:
    - filippo.valsorda@gmail.com
    - phihag@phihag.de
    - yasoob.khld@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
